export const openApiBaseSchemas = {
      ErrorResponse: {
        type: "object",
        description: "Standard JSON error body returned by API routes.",
        required: ["error"],
        properties: {
          error: { type: "string", example: "Item not found" },
        },
      },
      ProgramKind: {
        type: "string",
        description: "Top-level category encoded in a program item id.",
        enum: ["session", "talk", "poster"],
      },
      Ranking: {
        type: "object",
        description: "Recommendation ranking metadata for an item, when available.",
        required: ["rank", "score", "source", "topClusters"],
        properties: {
          rank: { type: "integer", description: "One-based rank within the recommendation set.", example: 1 },
          score: { type: "number", description: "Recommendation score from the similarity pipeline.", example: 0.84 },
          source: { type: "string", description: "Ranking source.", example: "similarity" },
          topClusters: {
            type: "array",
            description: "Highest-scoring topic clusters associated with this ranking.",
            items: {
              type: "object",
              required: ["clusterId", "score"],
              properties: {
                clusterId: { type: "string", example: "0" },
                score: { type: "number", example: 0.72 },
              },
            },
          },
        },
      },
      ProgramItem: {
        type: "object",
        description: "A session, talk, poster, break, meal, or other schedule item.",
        required: [
          "id",
          "sourceId",
          "kind",
          "title",
          "abstract",
          "type",
          "dayKey",
          "dayLabel",
          "time",
          "startH",
          "endH",
          "room",
          "presenter",
          "chair",
          "authors",
          "url",
          "sessionId",
          "sessionTitle",
          "posterNum",
          "ranking",
        ],
        properties: {
          id: { type: "string", description: "Stable item id in `kind:sourceId` format.", example: "session:m-brk0" },
          sourceId: { type: "string", description: "Source id without the kind prefix.", example: "m-brk0" },
          kind: { $ref: "#/components/schemas/ProgramKind" },
          title: { type: "string", description: "Display title.", example: "Registration & Coffee" },
          abstract: { type: "string", description: "Abstract text when available; otherwise an empty string." },
          type: { type: "string", description: "More specific program type from the extracted data.", example: "break" },
          dayKey: { type: "string", description: "Short day key used by frontend routes.", example: "mon" },
          dayLabel: { type: "string", description: "Human-readable day label.", example: "Mon June 1" },
          time: { type: "string", description: "Human-readable time range.", example: "8 AM - 9 AM" },
          startH: { type: ["number", "null"], description: "Start hour in 24-hour local conference time, or null if unknown.", example: 8 },
          endH: { type: ["number", "null"], description: "End hour in 24-hour local conference time, or null if unknown.", example: 9 },
          room: { type: "string", description: "Room or venue label. Empty string means no room was extracted.", example: "Amesbury Ballroom" },
          presenter: { type: "string", description: "Presenter text for talks or posters, if available." },
          chair: { type: "string", description: "Chair text for chaired sessions, if available." },
          authors: { type: "string", description: "Author list text, if available." },
          url: { type: "string", description: "Source URL if present in the extracted program data." },
          sessionId: { type: "string", description: "Parent session id for talks, if available." },
          sessionTitle: { type: "string", description: "Parent session title for talks, if available." },
          posterNum: { type: ["integer", "null"], description: "Poster number for posters, or null for non-poster items." },
          talkCount: { type: "integer", description: "Number of talks in this session, when the item is a session." },
          talkIndex: { type: ["integer", "null"], description: "One-based talk order within the session, when available." },
          ranking: {
            description: "Recommendation ranking metadata, or null if the item is not ranked.",
            anyOf: [{ $ref: "#/components/schemas/Ranking" }, { type: "null" }],
          },
        },
      },
} as const;
